### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by psjbeisler** [jmechnich/python-presence#1]
i was looking to use this (or fork it if there is no interest in continued support), but was looking for some basic usage or documentation as a boiler-plate.
Clearly python 2-3 will be an issue, but shouldn't be bad if built in a docker container, as-is, first before migrating.
Currently, only a few GUI clients support XEP-0174 and there is no other support for a CLI client library.

**Comment by jmechnich** [comment]
Hey there!

Thanks for your interest. I have not been using this in a while but it should be possible to do a few updates...
Let me get back to you after I looked at it.

**Comment by jmechnich** [comment]
I just noticed that I never wrote a reply after updating the code back in the day. Hopefully you have noticed the changes yourself back in the day and found them useful.

Closing due to age.
